#!/bin/sh

# Installs Certs generated by Acme AutoCerts
# into the Freenas Server

# Source Cert Info
. /root/scripts/certs.sh

# Server Info
REMOTE_HOST="freenas"
REMOTE="root@${REMOTE_HOST}"
CERTS_DIR="/root/certs"
REMOTE_TARGET="$REMOTE:$CERTS_DIR"

# Certs
CERT_NAME="bradenmars_wildcard"
R_CERT="$REMOTE_TARGET/$CERT_NAME.crt"
R_KEY="$REMOTE_TARGET/$CERT_NAME.key"
R_CA="$REMOTE_TARGET/CA/Acmecert.crt"

echo "Creating remote directories..."
ssh "$REMOTE" rm -rf "$CERTS_DIR"
ssh "$REMOTE" mkdir -p "$CERTS_DIR/CA"

echo "Copying Certs..."
scp "$CERT" "$R_CERT"
scp "$KEY" "$R_KEY"
scp "$CA" "$R_CA"

echo "Listing remote directory"
ssh "$REMOTE" ls -al $CERTS_DIR

echo "Done!"
echo "[FREENAS] Generated and Installed Certs on: $DATE" >>"$LOGFILE"
