#!/bin/sh

# Installs Certs generated by Acme AutoCerts
# into the Unifi Controller

# Source Cert Info
. /root/scripts/certs.sh

# Directories
UNIFI="/usr/local/UniFi"

# Cert Files
KEYOUT="$ACME/unifi.p12"

# Output
KEYSTORE="$UNIFI/data/keystore"

# Generate .p12 private key
echo "Generating .p12 key..."
openssl pkcs12 -export \
    -in "$CERT" \
    -inkey "$KEY" \
    -out "$KEYOUT" \
    -name unifi \
    -CAfile "$CA" \
    -caname root \
    -passout pass:test1234

# Import Key
echo "Importing Keystore..."
yes Y | keytool -importkeystore \
    -deststorepass aircontrolenterprise \
    -destkeypass aircontrolenterprise \
    -destkeystore "$KEYSTORE" \
    -srckeystore "$KEYOUT" \
    -srcstoretype PKCS12 \
    -alias unifi \
    -srcstorepass test1234

# Restarting UniFi
sleep 1
echo "Restarting UniFi..."
service unifi.sh stop
sleep 4
service unifi.sh start

echo "[UNIFI] Generated and Installed Keystore on: $DATE" >>"$LOGFILE"
